/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Booking (
  adu: Option[Int] = None,
  bookingDate: Option[Date] = None,
  bookingReference: Option[String] = None,
  curency: Option[String] = None,
  inf: Option[Int] = None,
  paxName: Option[String] = None,
  status: Option[String] = None,
  total: Option[Int] = None,
  travelDate: Option[Date] = None
) extends ApiModel


