/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetTourRates (
  externalReference: Option[Int] = None,
  timestamp: String,
  userEmail: String,
  userPwd: String,
  currency: String,
  languageCode: String,
  tourId: Int,
  tourOption: Int,
  validFrom: Date
) extends ApiModel


