/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina SoapUI - https://www.tangol.com/webservices/tangoltours.svc?wsdl
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetTourQuotation (
  externalReference: Option[Int] = None,
  timestamp: String,
  userEmail: String,
  userPwd: String,
  reqStatus: Option[Seq[ReqStatus]] = None,
  adu: Int,
  bookingDate: String,
  chd: Int,
  cpl: Int,
  currency: String,
  dbl: Int,
  discount: Int,
  inf: Int,
  languageCode: String,
  sgl: Int,
  tourId: Int,
  tourOptionCode: Int,
  tpl: Int
) extends ApiModel


