/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina SoapUI - https://www.tangol.com/webservices/tangoltours.svc?wsdl
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetTourQuotationResult (
  externalReference: Option[Int] = None,
  timestamp: Option[String] = None,
  userEmail: Option[String] = None,
  userPwd: Option[String] = None,
  reqStatus: Option[Seq[ReqStatus]] = None,
  /* int32 */
  adu: Option[Int] = None,
  bookingDate: Option[String] = None,
  /* int32 */
  chd: Option[Int] = None,
  /* int32 */
  commission: Option[Int] = None,
  /* int32 */
  dbl: Option[Int] = None,
  /* int32 */
  discount: Option[Int] = None,
  /* int32 */
  inf: Option[Int] = None,
  languageCode: Option[String] = None,
  /* float */
  netRate: Option[Double] = None,
  /* float */
  rackRate: Option[Double] = None,
  /* int32 */
  sgl: Option[Int] = None,
  tourDescription: Option[String] = None,
  /* int32 */
  tourId: Option[Int] = None,
  /* int32 */
  tourOptionCode: Option[Int] = None,
  tourOptionDescription: Option[String] = None,
  /* int32 */
  tpl: Option[Int] = None
) extends ApiModel


