/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InfoTour (
  /* string */
  currency: Option[String] = None,
  /* string */
  duration: Option[String] = None,
  listMonths: Option[Seq[Months]] = None,
  /* int32 */
  minRate: Option[Int] = None,
  /* string */
  name: Option[String] = None,
  /* string */
  subTypeCode: Option[String] = None,
  /* int32 */
  tourId: Option[Int] = None,
  /* string */
  tourType: Option[String] = None,
  /* string */
  typeCode: Option[String] = None,
  /* string */
  urlHomePic: Option[String] = None,
  /* string */
  urlTour: Option[String] = None
) extends ApiModel


