/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MakeBookingResult (
  externalReference: Option[Boolean] = None,
  timeStamp: Option[String] = None,
  userEmail: Option[Boolean] = None,
  userPwd: Option[Boolean] = None,
  reqStatus: Option[Seq[ReqStatus]] = None,
  bookingConfirmation: Option[String] = None,
  bookingReference: Option[String] = None,
  currency: Option[String] = None,
  languageCode: Option[String] = None,
  modoTest: Option[Boolean] = None,
  totalCommission: Option[Int] = None,
  totalNettAmount: Option[Int] = None,
  totalRackAmount: Option[Int] = None,
  listTourBookingResponse: Option[MakeBookingResultListTourBookingResponse] = None
) extends ApiModel


