/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TourBookingResponse (
  externalReference: Option[Boolean] = None,
  timeStamp: Option[Date] = None,
  userEmail: Option[Boolean] = None,
  userPwd: Option[Boolean] = None,
  reqStatus: Option[Seq[ReqStatus]] = None,
  adu: Option[Int] = None,
  bookingDate: Option[Date] = None,
  chd: Option[Int] = None,
  commission: Option[Int] = None,
  currency: Option[String] = None,
  dbl: Option[Int] = None,
  discount: Option[Int] = None,
  inf: Option[Int] = None,
  languageCode: Option[String] = None,
  nettRate: Option[Float] = None,
  pickUpLocation: Option[String] = None,
  pickUpTime: Option[Date] = None,
  rackRate: Option[Float] = None,
  sgl: Option[Int] = None,
  tourDescription: Option[String] = None,
  tourId: Option[Int] = None,
  tourLanguageCode: Option[String] = None,
  tourOptionCode: Option[String] = None,
  tourOptionDescription: Option[String] = None,
  tpl: Option[Int] = None
) extends ApiModel


