/**
 * Tangol API Documentation SOAP
 * This a documentation for web service WSDL from Tangol Tours SRL, Argentina SoapUI - https://www.tangol.com/webservices/tangoltours.svc?wsdl
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Traveller (
  ageBand: Option[Int] = None,
  birthDate: Option[String] = None,
  docExpirationDate: Option[String] = None,
  docIssueDate: Option[String] = None,
  docNumber: Option[String] = None,
  docType: Option[String] = None,
  email: Option[String] = None,
  firstName: Option[String] = None,
  gender: Option[String] = None,
  hotel: Option[String] = None,
  lastName: Option[String] = None,
  nationallity: Option[String] = None,
  phone: Option[String] = None
) extends ApiModel


